/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraapp;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author baxx
 */
public class Vcalculadora extends javax.swing.JFrame {
    private String acumulado="";
    private String ingresado="", signo="";
    boolean op=false, activado= true, punto=false;
   
    private double aux1=0, aux2=0;
    
    /**
     * Creates new form Vcalculadora
     */
    public Vcalculadora() {
        initComponents();
        this.setSize(300, 450);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        etiquetaGuardado = new javax.swing.JLabel();
        etiquetaInRes = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnMinum = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnPlusMinum = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        calculadoraMI = new javax.swing.JMenuItem();
        conversorMI = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salirMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setPreferredSize(new java.awt.Dimension(300, 450));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        etiquetaGuardado.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        etiquetaGuardado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(etiquetaGuardado, gridBagConstraints);

        etiquetaInRes.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N
        etiquetaInRes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaInRes.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(etiquetaInRes, gridBagConstraints);

        btnClear.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnClear, gridBagConstraints);

        btnSquare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareRoot20.png"))); // NOI18N
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnSquare, gridBagConstraints);

        btnDivide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/divide20.png"))); // NOI18N
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnDivide, gridBagConstraints);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete20.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnBorrar, gridBagConstraints);

        btnSeven.setBackground(new java.awt.Color(102, 102, 102));
        btnSeven.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnSeven, gridBagConstraints);

        btnEight.setBackground(new java.awt.Color(102, 102, 102));
        btnEight.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnEight, gridBagConstraints);

        btnNine.setBackground(new java.awt.Color(102, 102, 102));
        btnNine.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnNine, gridBagConstraints);

        btnMulti.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnMulti.setText("X");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnMulti, gridBagConstraints);

        btnFour.setBackground(new java.awt.Color(102, 102, 102));
        btnFour.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnFour, gridBagConstraints);

        btnFive.setBackground(new java.awt.Color(102, 102, 102));
        btnFive.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnFive, gridBagConstraints);

        btnSix.setBackground(new java.awt.Color(102, 102, 102));
        btnSix.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnSix, gridBagConstraints);

        btnMinum.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnMinum.setText("-");
        btnMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnMinum, gridBagConstraints);

        btnOne.setBackground(new java.awt.Color(102, 102, 102));
        btnOne.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnOne, gridBagConstraints);

        btnTwo.setBackground(new java.awt.Color(102, 102, 102));
        btnTwo.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnTwo, gridBagConstraints);

        btnThree.setBackground(new java.awt.Color(102, 102, 102));
        btnThree.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnThree, gridBagConstraints);

        btnPlus.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnPlus, gridBagConstraints);

        btnPlusMinum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plusMinus20.png"))); // NOI18N
        btnPlusMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnPlusMinum, gridBagConstraints);

        btnZero.setBackground(new java.awt.Color(102, 102, 102));
        btnZero.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnZero, gridBagConstraints);

        btnDot.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnDot, gridBagConstraints);

        btnEquals.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(btnEquals, gridBagConstraints);

        menu1.setText("Usos");

        calculadoraMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        calculadoraMI.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        calculadoraMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculator20.png"))); // NOI18N
        calculadoraMI.setText("Calculadora");
        calculadoraMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraMIActionPerformed(evt);
            }
        });
        menu1.add(calculadoraMI);

        conversorMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        conversorMI.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        conversorMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/convert20.png"))); // NOI18N
        conversorMI.setText("Conversor de Divisas");
        conversorMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversorMIActionPerformed(evt);
            }
        });
        menu1.add(conversorMI);
        menu1.add(jSeparator1);

        salirMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salirMI.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        salirMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit20.jpg"))); // NOI18N
        salirMI.setText("Salir");
        salirMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMIActionPerformed(evt);
            }
        });
        menu1.add(salirMI);

        barraMenu.add(menu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMIActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMIActionPerformed

    private void calculadoraMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraMIActionPerformed
      JOptionPane.showMessageDialog(null, "Ya estas en la calculadora");
    }//GEN-LAST:event_calculadoraMIActionPerformed

    private void conversorMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversorMIActionPerformed
       VConversor vCon = new VConversor();
       vCon.setVisible(true);
       dispose();
    }//GEN-LAST:event_conversorMIActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        ingresado="";
        signo="";
        aux1=aux2=0;
        
        etiquetaGuardado.setText("");
        etiquetaInRes.setText("0");
        punto= false;
        
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
       ingresado+="7";
       etiquetaInRes.setText(ingresado);
       activado=true;
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
       ingresado+="4";
       etiquetaInRes.setText(ingresado);
       activado=true;
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        ingresado+="1";
        etiquetaInRes.setText(ingresado);
        activado=true;
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
       
        if(ingresado!=""){
            ingresado+="0";
            etiquetaInRes.setText(ingresado);
        }
        activado=true;
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        ingresado+="2";
        etiquetaInRes.setText(ingresado);
        activado=true;
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        ingresado+="5";
        etiquetaInRes.setText(ingresado);
        activado=true;
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
       ingresado+="8";
       etiquetaInRes.setText(ingresado);
       activado=true;
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        ingresado+="9";
        etiquetaInRes.setText(ingresado);
        activado=true;
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        ingresado+="6";
        etiquetaInRes.setText(ingresado);
        activado=true;
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        ingresado+="3";
        etiquetaInRes.setText(ingresado);
        activado=true;
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
       if(  punto== false ){
       
           
           
           if(ingresado==""){
           ingresado+="0.";
            etiquetaInRes.setText(ingresado);
            }else{



                    ingresado+=".";
                     etiquetaInRes.setText(ingresado);


            }
           punto=true;
       }
        
        
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        
        
        if(ingresado!=""){
            aux1 = Double.parseDouble(ingresado);
            etiquetaGuardado.setText("sqrt("+ingresado+")");
            aux2= Math.sqrt(aux1);
            etiquetaInRes.setText("= "+ String.format("%.2f", aux2));
            ingresado="";
                
            aux1= aux2;
            aux2=0;

        }else{
                
                
            etiquetaGuardado.setText("sqrt("+String.format("%.2f", aux1)+")");
            aux2= Math.sqrt(aux1);
            etiquetaInRes.setText("= "+ String.format("%.2f", aux2));
                 
            aux1= aux2;
            aux2=0;
                
        }

        
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        String auxS="";
        
        if(activado){
        if(op==true){
             auxS=""+aux1+signo+ingresado;
            
            switch (signo) {
                case "+":
                    aux2= aux1 +(Double.parseDouble(ingresado));
                    break;
                    
                case "-":
                    aux2= aux1 -(Double.parseDouble(ingresado));
                    break;
                case "/":
                    aux2= aux1 /(Double.parseDouble(ingresado));
                    break;
                case "*":
                    aux2= aux1 *(Double.parseDouble(ingresado));
                    break;
                
                default:
                    throw new AssertionError();
            }

            ingresado = auxS; 
             op=false;
            
        }else{
            aux1 = aux2= Double.parseDouble(ingresado);
            
        }
         etiquetaGuardado.setText(ingresado);
         etiquetaInRes.setText("="+ String.format("%.2f", aux2) );
         ingresado= ""+ aux2;
         aux1= aux2;
         aux2=0;
         punto=true;
         activado=true;
         signo="";
        }
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
       
        if(activado){
            
            if(ingresado!= ""){
                aux1= Double.parseDouble(ingresado);
                signo="+";
                ingresado+="+";
                 etiquetaGuardado.setText(ingresado);
                 etiquetaInRes.setText("");
                 ingresado="";
                op=true;
            }else{
                if(aux1!=0){
                    
                        signo="+";
                       ingresado= ""+aux1+" + ";
                       etiquetaGuardado.setText(ingresado);
                       ingresado="";
                       op=true;
                }
            
            }
            
        }
        
        activado=false;
        
        
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinumActionPerformed
        if(activado){
             if(ingresado != ""){
                aux1= Double.parseDouble(ingresado);
                signo="-";
               ingresado+="-";
                etiquetaGuardado.setText(ingresado);
                etiquetaInRes.setText("");
                ingresado="";
               op=true;
            } else if(ingresado == ""){
                aux1= 0;

                ingresado+="-";
                 etiquetaInRes.setText(ingresado);

                op=false;

            }
             activado=false;
        }
        
       
       
        
    }//GEN-LAST:event_btnMinumActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
    
       
       if(activado){
             if(ingresado != ""){
                aux1= Double.parseDouble(ingresado);
                signo="*";

                 etiquetaGuardado.setText(ingresado +="X");
                 etiquetaInRes.setText("");
                 ingresado="";
                 op=true;
                 punto=true;
            } 
             activado=false;
        }
        
       
       
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
       
        if(ingresado != ""){
            if (ingresado.length()==1) {
                ingresado="";
                etiquetaInRes.setText("0");
            }else{
                ingresado =ingresado.substring(0, ingresado.length()-1);
                etiquetaInRes.setText(ingresado);
            }
        }
        

       
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        
        
          if(activado){
             if(ingresado != ""){
                aux1= Double.parseDouble(ingresado);
                signo="/";
                ingresado+=" / ";
                 etiquetaGuardado.setText(ingresado);
                 etiquetaInRes.setText("");
                 ingresado="";
                 op=true;
                
            } 
             activado=false;
        }
        
        
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnPlusMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinumActionPerformed
        
       if(ingresado.charAt(0)=='-'){
           ingresado= ingresado.substring(1, ingresado.length());
       }else{
           ingresado= "-"+ingresado;
       }
       etiquetaInRes.setText(ingresado);
       
    }//GEN-LAST:event_btnPlusMinumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vcalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vcalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vcalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vcalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            /* Create and display the form */
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vcalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Vcalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Vcalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Vcalculadora.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vcalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMinum;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlusMinum;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JMenuItem calculadoraMI;
    private javax.swing.JMenuItem conversorMI;
    private javax.swing.JLabel etiquetaGuardado;
    private javax.swing.JLabel etiquetaInRes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuItem salirMI;
    // End of variables declaration//GEN-END:variables
}
