/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraapp;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author baxx
 */
public class VConversor extends javax.swing.JFrame {

    private double factorConversion=1, cantidadAconvertir=0, cambio=0;
    private String cadenaIngresada ="", convertirDe="cop",convertirA="us";
    private boolean punto=false;
    
    
    
    public VConversor() {
        initComponents();
        this.setSize(300, 450);
        setLocationRelativeTo(null);
        hallarFactorConversion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        etiquetaIngreso = new javax.swing.JLabel();
        comboOriginal = new javax.swing.JComboBox<>();
        etiquetaConvertida = new javax.swing.JLabel();
        comboAConvertir = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        simboloDivisa1 = new javax.swing.JLabel();
        simboloDivisa2 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        calculadoraMI = new javax.swing.JMenuItem();
        conversorMI = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salirMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de divisas");

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 450));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        etiquetaIngreso.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        etiquetaIngreso.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(etiquetaIngreso, gridBagConstraints);

        comboOriginal.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        comboOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colombia - Peso", "Estados Unidos - Dolár", "Europa - Euro", "Reino unido - Libras Esterlinas" }));
        comboOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOriginalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(comboOriginal, gridBagConstraints);

        etiquetaConvertida.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        etiquetaConvertida.setText("00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(etiquetaConvertida, gridBagConstraints);

        comboAConvertir.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        comboAConvertir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados Unidos - Dolár", "Europa - Euro", "Reino unido - Libras Esterlinas", "Colombia - Peso" }));
        comboAConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAConvertirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(comboAConvertir, gridBagConstraints);

        btnClear.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnClear, gridBagConstraints);

        btnBorrar.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete20.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnBorrar, gridBagConstraints);

        btnUno.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnUno.setText("1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnUno, gridBagConstraints);

        btnDos.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnDos.setText("2");
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnDos, gridBagConstraints);

        btnTres.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnTres.setText("3");
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnTres, gridBagConstraints);

        btnCuatro.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnCuatro.setText("4");
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnCuatro, gridBagConstraints);

        btnCinco.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnCinco.setText("5");
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnCinco, gridBagConstraints);

        btnSeis.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnSeis.setText("6");
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnSeis, gridBagConstraints);

        btnSiete.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnSiete.setText("7");
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnSiete, gridBagConstraints);

        btnOcho.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnOcho.setText("8");
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnOcho, gridBagConstraints);

        btnNueve.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnNueve.setText("9");
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnNueve, gridBagConstraints);

        btnCero.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnCero.setText("0");
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnCero, gridBagConstraints);

        btnDot.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(btnDot, gridBagConstraints);

        simboloDivisa1.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        simboloDivisa1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        simboloDivisa1.setText("COP $");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(simboloDivisa1, gridBagConstraints);

        simboloDivisa2.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        simboloDivisa2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        simboloDivisa2.setText("US $");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(simboloDivisa2, gridBagConstraints);

        menu1.setText("Usos");

        calculadoraMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        calculadoraMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculator20.png"))); // NOI18N
        calculadoraMI.setText("Calculadora");
        calculadoraMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraMIActionPerformed(evt);
            }
        });
        menu1.add(calculadoraMI);

        conversorMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        conversorMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/convert20.png"))); // NOI18N
        conversorMI.setText("Conversor de divisas");
        conversorMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversorMIActionPerformed(evt);
            }
        });
        menu1.add(conversorMI);
        menu1.add(jSeparator1);

        salirMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salirMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit20.jpg"))); // NOI18N
        salirMI.setText("Salir");
        salirMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMIActionPerformed(evt);
            }
        });
        menu1.add(salirMI);

        barraMenu.add(menu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMIActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMIActionPerformed

    private void calculadoraMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraMIActionPerformed
       Vcalculadora v = new Vcalculadora();
       v.setVisible(true);
       dispose();
    }//GEN-LAST:event_calculadoraMIActionPerformed

    private void conversorMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversorMIActionPerformed
        JOptionPane.showMessageDialog(null, "Ya estas en el conversor de divisas");
    }//GEN-LAST:event_conversorMIActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        cadenaIngresada+= "1";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        cadenaIngresada+= "7";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        cadenaIngresada+= "2";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        cadenaIngresada+= "3";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        cadenaIngresada+= "4";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
       cadenaIngresada+= "5";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        cadenaIngresada+= "6";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        cadenaIngresada+= "8";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
       cadenaIngresada+= "9";
        etiquetaIngreso.setText(cadenaIngresada);
        convertir();
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        
        if (cadenaIngresada!="") {
                cadenaIngresada+= "0";
                etiquetaIngreso.setText(cadenaIngresada);
                convertir();
        }
        
        
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        
        if(punto==false){
            
            if (cadenaIngresada!="") {
                cadenaIngresada+= ".";
                
            }else{
                cadenaIngresada+= "0.";
            }
            etiquetaIngreso.setText(cadenaIngresada);
            punto=true;
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cadenaIngresada="";
        etiquetaIngreso.setText("0");
        etiquetaConvertida.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if (cadenaIngresada!="") {
                if(cadenaIngresada.length()==1){
                cadenaIngresada+= "";
                etiquetaIngreso.setText("0");
                etiquetaConvertida.setText("0");
            }else{
                cadenaIngresada = cadenaIngresada.substring(0, cadenaIngresada.length()-1);
                etiquetaIngreso.setText(cadenaIngresada);
                convertir();
            }
        }
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void comboOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOriginalActionPerformed
        if (comboOriginal.getSelectedIndex()==0) {
            convertirDe="cop";
            simboloDivisa1.setText("COP $");
        }else if (comboOriginal.getSelectedIndex()==1) {
            convertirDe="us";
            simboloDivisa1.setText("US $");
        }else if (comboOriginal.getSelectedIndex()==2) {
            convertirDe="eur";
            simboloDivisa1.setText("EUR €");
        }else if (comboOriginal.getSelectedIndex()==3) {
            convertirDe="gbp";
            simboloDivisa1.setText("GBP £");
        }
        System.out.println(convertirDe);
        convertir();
    }//GEN-LAST:event_comboOriginalActionPerformed

    private void comboAConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAConvertirActionPerformed
       if (comboAConvertir.getSelectedIndex()==0) {
            convertirA="us";
            simboloDivisa2.setText("US $");
        }else if (comboAConvertir.getSelectedIndex()==1) {
            convertirA="eur";
            simboloDivisa2.setText("EUR €");
        }else if (comboAConvertir.getSelectedIndex()==2) {
            convertirA="gbp";
            simboloDivisa2.setText("GBP £");
        }else if (comboAConvertir.getSelectedIndex()==3) {
            convertirA="cop";
            simboloDivisa2.setText("COP $");
        }
       System.out.println("convertir a "+convertirA);
       
       convertir();
    }//GEN-LAST:event_comboAConvertirActionPerformed
    private void hallarFactorConversion(){
      if(convertirDe.equalsIgnoreCase(convertirA)){
          factorConversion=1;
      }else if(convertirDe.equalsIgnoreCase("cop")&& convertirA.equals("us")){
          factorConversion=0.00020;
      }else if(convertirDe.equalsIgnoreCase("cop")&& convertirA.equals("eur")){
          factorConversion=0.000203;
      }else if(convertirDe.equalsIgnoreCase("cop")&& convertirA.equals("gbp")){
          factorConversion=0.00018;
      }else if(convertirDe.equalsIgnoreCase("us")&& convertirA.equals("cop")){
          factorConversion=5007.51;
      }else if(convertirDe.equalsIgnoreCase("us")&& convertirA.equals("eur")){
          factorConversion=1.0167;
      }else if(convertirDe.equalsIgnoreCase("us")&& convertirA.equals("gbp")){
          factorConversion=0.8763;
          
      }else if(convertirDe.equalsIgnoreCase("eur")&& convertirA.equals("cop")){
          factorConversion=4914.000;
      }else if(convertirDe.equalsIgnoreCase("eur")&& convertirA.equals("us")){
          factorConversion=0.9833;
      }else if(convertirDe.equalsIgnoreCase("eur")&& convertirA.equals("gbp")){
          factorConversion=0.8615;
      }else if(convertirDe.equalsIgnoreCase("gbp")&& convertirA.equals("cop")){
          factorConversion=5704.000;
      }else if(convertirDe.equalsIgnoreCase("gbp")&& convertirA.equals("eur")){
          factorConversion=1.0167;
      }else if(convertirDe.equalsIgnoreCase("gbp")&& convertirA.equals("us")){
          factorConversion=1.1603;
      }
      
    
    }
    
    private void convertir(){
        hallarFactorConversion();
        cantidadAconvertir= Double.parseDouble(etiquetaIngreso.getText()) ;
        cambio = cantidadAconvertir * factorConversion;
        
        etiquetaConvertida.setText(String.format("%.2f", cambio));
    
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            /* Create and display the form */
            
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VConversor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VConversor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VConversor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VConversor.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JMenuItem calculadoraMI;
    private javax.swing.JComboBox<String> comboAConvertir;
    private javax.swing.JComboBox<String> comboOriginal;
    private javax.swing.JMenuItem conversorMI;
    private javax.swing.JLabel etiquetaConvertida;
    private javax.swing.JLabel etiquetaIngreso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuItem salirMI;
    private javax.swing.JLabel simboloDivisa1;
    private javax.swing.JLabel simboloDivisa2;
    // End of variables declaration//GEN-END:variables
}
